### PR TITLE
update to rxjs 6 and angular 6

### PR DESCRIPTION
**Pull request by vitaliy-patsay**
Hi,

Rx changed their import statements. Looks like these changes should be enough to make module compatible with Angular 6 and RxJs 6. Some versioning changes of this package should be also made

### CODE REVIEW

**Comment by szbartnik** [comment]
Hi,

Thank you for your contribution! I'll take a look on your PR this weekend. I have also to add some notes to README mentioning starting new version at least `rxjs 5.6.0-forward-compat.4` will be required

**Comment by szbartnik** [comment]
@vitaliy-patsay I'm not able to push to your fork branch. I have a small fix in peer dependencies and update of README file. Please see attached screenshot to see how allow me pushing to your fork branch:
img

**Comment by vitaliy-patsay** [comment]
It's checked @kneefer. So you should be able to make edits if I understand this flag correct. 
 screenshot

**Comment by szbartnik** [comment]
Ok... now i see it. You forked not directly from `kneefer/ngx-translate-resx-http-loader` but from `KwintenP/ngx-translate-resx-http-loader`... So only KwintenP is able to push changes to your fork. Now we have 3 options:
- Create new, direct fork from my repo and I will be able to apply my changes to your repo
- Add me as a collaborator to your existing fork temporarily so I can push to your fork
- I can create new branch on my repo and merge your changes and apply mine and recreate PR (but I don't like it since it is more transparent in history when it's visible that PR was initiated by you)

**Comment by vitaliy-patsay** [comment]
Done, I've added you as collaborator.

**Comment by szbartnik** [comment]
Thanks @vitaliy-patsay Now we have to wait for TravisCI deployment build but it may take a while since they are experiencing some problems today: https://www.traviscistatus.com/

**Comment by szbartnik** [comment]
Ok, v2.0.1 is now on NPM. Thanks @vitaliy-patsay once more. Let me know if something is wrong ;)

**Pull request merged**
